### ISSUE TITLE
Build instructions/Requirements missing

### ISSUE THREAD

**Issue by ketzu** [Ma-Ko-dev/Sheepy#1]
Hey, the repo leaves the requirements for sheepy unclear.

Traditionally there should be a requirements.txt file containing all the requirements to run sheepy, e.g., playsound.

This allows installing all requirements using `pip install -r requirements.txt`.

You can generate one in your virtual environment using `python -m pip freeze` and put it in the file if you don't know them otherwise :)

**Comment by Ma-Ko-dev** [comment]
Hey!

Thank you. I used `pipreqs` to generate the rerequirements.txt and added it to the repo.

I will try to keep it updated.
